name: expense
networks: 
  default:
    name: expense
volumes:
  mysql:
    #external: true # if true, you need to create manually
       # docker volume create myqsl
services:
  mysql:
    image: akhila9122/mysql:v1.0
    container_name: mysql #--name mysql
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume
  backend:
    image: akhila9122/backend:v1.0
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: akhila9122/frontend:v1.0
    container_name: frontend
    depends_on:
    - backend
    ports:
    - "80:80"
